# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vHmv2huywwJLPEQabxVeZbF1MgB7gbPQ
"""

print("Hello word !")

"""Que legal meu primeiro programa."""

print("Então vamos avançar.")
